In [21]:
from sklearn.ensemble import AdaBoostClassifier
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import GridSearchCV

In [22]:
df = pd.read_csv("A2_data.csv")

In [23]:
# drop row 79543
df = df.drop(79543, axis=0)

In [24]:
features = df.drop(['class','field_ID','plate','MJD'], axis=1)
labels =df['class']
key=features.keys()

In [25]:
#split the dataset
x_train, x_test, y_train, y_test = train_test_split(features, labels, test_size=0.3, random_state=123, stratify=labels)


In [8]:
clf = AdaBoostClassifier(random_state=123)

In [35]:
parameters = {
    'n_estimators': [5,10,20,30,50,70],
    'learning_rate': [0.1,0.3,0.5,0.8,1],
    'algorithm': ['SAMME', 'SAMME.R']
}
gr_ada = GridSearchCV(clf, parameters, cv=5, verbose=2, n_jobs=-1)
gr_ada.fit(x_train, y_train)

Fitting 5 folds for each of 60 candidates, totalling 300 fits


GridSearchCV(cv=5,
             estimator=AdaBoostClassifier(algorithm='SAMME', n_estimators=30),
             n_jobs=-1,
             param_grid={'algorithm': ['SAMME', 'SAMME.R'],
                         'learning_rate': [0.1, 0.3, 0.5, 0.8, 1],
                         'n_estimators': [5, 10, 20, 30, 50, 70]},
             verbose=2)

In [36]:
gr_ada.best_params_

{'algorithm': 'SAMME.R', 'learning_rate': 0.8, 'n_estimators': 70}

In [26]:
clf = AdaBoostClassifier(
    algorithm = 'SAMME.R',
    learning_rate = 0.8,
    n_estimators = 70
)
clf.fit(x_train, y_train)

AdaBoostClassifier(learning_rate=0.8, n_estimators=70)

In [27]:
#Best Parameters
from sklearn.model_selection import cross_val_score

cross_score = cross_val_score(clf,features,labels,cv = 5,scoring = "accuracy")
print(f' Scores for each fold are: {cross_score}')
print(f' Average score: {"{:.2f}".format(cross_score.mean())}')

 Scores for each fold are: [0.7652     0.7756     0.7714     0.7753     0.77498875]
 Average score: 0.77


In [28]:
clf = AdaBoostClassifier(
    algorithm = 'SAMME.R',
    learning_rate = 0.8,
    n_estimators = 1
)
clf.fit(x_train, y_train)

AdaBoostClassifier(learning_rate=0.8, n_estimators=1)

In [29]:
#Experiment 1
from sklearn.model_selection import cross_val_score

cross_score = cross_val_score(clf,features,labels,cv = 5,scoring = "accuracy")
print(f' Scores for each fold are: {cross_score}')
print(f' Average score: {"{:.2f}".format(cross_score.mean())}')

 Scores for each fold are: [0.6434     0.63805    0.658      0.6471     0.64253213]
 Average score: 0.65


In [19]:
y_pred = clf.predict(x_test)
sortedlabels = clf.classes_

In [20]:
from sklearn.metrics import classification_report, confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(classification_report(y_test, y_pred))
print(cm)

              precision    recall  f1-score   support

      GALAXY       0.83      0.93      0.87     17834
         QSO       0.69      0.76      0.72      5688
        STAR       0.65      0.38      0.48      6478

    accuracy                           0.78     30000
   macro avg       0.72      0.69      0.69     30000
weighted avg       0.76      0.78      0.76     30000

[[16509   555   770]
 [  822  4336   530]
 [ 2628  1400  2450]]
